# Generated by Django 2.2 on 2019-05-23 10:21

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='new user', max_length=100)),
                ('password', models.CharField(default='admin', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NoteApp',
            fields=[
                ('userID', djongo.models.fields.ObjectIdField(auto_created=True, default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('name', models.CharField(default='new user', max_length=50)),
                ('lname', models.CharField(default='new user', max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('username', models.CharField(default='new user', max_length=100)),
                ('photoUrl', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
