# Generated by Django 2.2.1 on 2019-07-01 22:07

import Backend.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteapp',
            name='password',
        ),
        migrations.AddField(
            model_name='noteapp',
            name='notesApp',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=Backend.models.Notes),
        ),
    ]
