# Generated by Django 2.2 on 2019-05-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20190526_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteapp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
