# Generated by Django 2.2.1 on 2019-07-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20190702_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteapp',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
