# Generated by Django 2.2.1 on 2019-05-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20190526_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteapp',
            name='password',
        ),
    ]
