# Generated by Django 2.2.1 on 2019-07-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20190702_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteapp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
