# Generated by Django 2.2.1 on 2019-07-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20190702_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteapp',
            name='id',
        ),
        migrations.AlterField(
            model_name='noteapp',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
